package onlineShoppingProject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class ConnectionProvider {
    public static Connection getCon() {
        try {
            // Define the database connection parameters
            String url = "jdbc:mysql://localhost:3306/ospjsp"; // JDBC URL for MySQL
            String username = "root"; // MySQL username
            String password = ""; // MySQL password (if applicable)

            // Load the MySQL JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            // Establish a connection to the database
            Connection con = DriverManager.getConnection(url, username, password);

            // Return the established connection
            return con;
        } catch (ClassNotFoundException | SQLException e) {
            // Print any exceptions that occur during the connection process
            System.out.println(e);
            System.out.print("The above error message was generated by this machine");

            // Return null to indicate a failed connection
            return null;
        }
    }
}
